---
title: "Github 사용법"
description: "Github 가입/사용법"
author: "BenKorea feat. ChatGPT"
date: "2024-10-25"
date-modified: last-modified
categories: [Github, manual]
---

## Github란?

GitHub는 Git을 기반으로 한 웹 기반 호스팅 서비스로, 소스 코드 관리와 협업을 위한 플랫폼입니다.
GitHub는 Git을 사용하여 프로젝트의 코드베이스를 중앙에서 관리하며, 개발자들이 효율적으로 코드 리뷰, 이슈 관리, 프로젝트 관리, 그리고 협업을 할 수 있도록 다양한 도구와 인터페이스를 제공합니다.
**Pull Request(PR)**를 통해 코드 변경 사항을 리뷰하고 병합할 수 있으며, **Continuous Integration/Continuous Deployment(CI/CD)**와 같은 자동화 기능을 지원해 소프트웨어 개발의 생산성과 품질을 높입니다.

## 매뉴얼

설치 및 사용에 대해서는 아래의 공식자료를 활용하시길 추천합니다.

-   공식문서(<https://docs.github.com/ko>)는 한글로도 번역되어 있습니다.

-    공식 Training manual (<https://githubtraining.github.io/training-manual/#/>)도 있습니다.

## Github 사용법

### 가입하기

-   Sign up하면 email을 입력해야 하는데 이미 등록된 이메일은 진행되지 않으므로 주의를 요합니다. (Git local setting에서 사용했던 email 사용을 추천합니다.)
-   비밀번호와 username을 입력을 진행합니다. (Git local setting에서 사용했던 username 사용을 추천합니다.)
-   이 때 8자리의 launch code를 email로 보내주는데 이를 가입화면에 입력해야 합니다.

### Repository 생성하기

-   `git_exercise`와 같은 원하는 Repository name을 입력하고 Public을 선택하여 `Create a new repositiry`를 진행하시면 됩니다.

### 원격저장소에 프로젝트 올리기

-   \<\> code 메뉴에서 Quick setup 내에 있는 URL을 이용하여 새로 만들어진 원격저장소로 local 저장소의 commit된 결과들을 push 하면 됩니다.
