project:
  type: website
  
profile:
  default: ko
  group: 
    - [ko, en]
    
website:
  title: "RPythonStudy"
  navbar:
    style: pinned
    logo: RPythonStudy_logo.png
    tools:
      - icon: github
        href: https://github.com/RPythonStudy/website
    left:
      - text: "Blog"
        href: index.qmd
      - text: "R"
        href: posts/R/introduction_to_R.qmd
      - text: "Python"
        href: posts/Python/introduction_to_Python.qmd
      - text: "Quarto"
        href: posts/Quarto/introduction_to_Quarto.qmd        
      - text: "Statistics"
        href: posts/statistics/introduction_to_statistics.qmd
      - text: "Quiz"        
        href: https://rpythonstudy.shinyapps.io/Quiz/
      - text: "Resources"      
        href: posts/Resources/introduction_to_resources.qmd
      - text: "Tools"      
        href: posts/tools/introduction_to_tools.qmd
      - text: "IT"      
        href: posts/IT/introduction_to_IT.qmd
      - text: "About"      
        href: posts/about/about.qmd    
        
  sidebar:
    - title: "R"
      contents:
        - posts/R/introduction_to_R.qmd
        - posts/R/R_setup.qmd
        - posts/R/RStudio_setup.qmd
        - section: "문법"
          contents:        
            - posts/R/syntax/R_syntax.qmd
            - posts/R/syntax/RegEx.qmd
            - posts/R/syntax/regular_expression.qmd
            - posts/R/syntax/basic.qmd
        - posts/R/outlier_detection.qmd   
        - posts/R/built_in_dataset.qmd
        - posts/R/Chi_square_test_in_R.qmd
        - section: "Shiny"
          contents:          
            - posts/R/shiny/shiny_example.qmd
            - posts/R/shiny/Hands_on_Shiny_website.qmd
    - title: "Python"
      contents:
        - posts/Python/introduction_to_Python.qmd
        - posts/Python-setup/Python_setup.qmd
        - posts/VSCode-setup/VSCode_setup.qmd    
    - title: "Quarto"
      contents:
        - posts/Quarto/introduction_to_Quarto.qmd
        - posts/Quarto/Quarto_setup.qmd
        - section: "Websites"
          contents:
            - posts/Quarto/Website/Hands_on_Quarto_Website.qmd
        - section: "Manuscripts"
          contents:            
            - posts/Quarto/Manuscript/manuscript_example.qmd
        - section: "기능구현"
          contents:            
            - posts/Quarto/Functions/tooltip.qmd
        
    - title: "Statistics"
      contents:
        - posts/statistics/introduction_to_statistics.qmd
        - posts/basic-statistics/basic_statistics.qmd
        - posts/survival-analysis/survival_analysis.qmd
        - posts/group-comparison/group_comparison.qmd
        - posts/Chi-square-test/Chi_square_test.qmd
    - title: "Resources"
      contents:
        - posts/Resources/introduction_to_resources.qmd
        - section: "공공데이터포털"
          contents:
            - posts/DataGoKr/DataGoKr.qmd
            - posts/DataGoKr/Hands_on_API_Shinyapp.qmd
    - title: "Tools"
      contents:
        - posts/tools/introduction_to_tools.qmd
        - section: "Git"
          contents:
            - posts/Git/Git_setup.qmd
            - posts/Git/Github.qmd
            - posts/Git/SSH.qmd            
            - posts/Git/Hands_on_Git.qmd


execute: 
  freeze: auto
  
format:
  html:
    theme: cosmo
    css: styles/styles.css
    csl: styles/nuclear-medicine-and-molecular-imaging.csl
    code-copy: true
    toc: true
    mathjax: "default"
    link-external-newwindow: true

resource-paths:
  - resources/
  - images/