---
title: "Introduciton"
description: "R 개발역사와 의학연구에서의 필요성"
author: "RPythonStudyGroup feat. ChatGPT"
date: "May 4, 2024"
date-modified: "May 4, 2024"
categories: [R, introduction]
---

### R 개발역사

R은 뉴질랜드 오클랜드 대학교의 Ross Ihaka와 Robert Gentleman에 의해 개발되었으며, 1993년에 처음 출시되었습니다. 이 언어는 Bell Laboratories의 John Chambers 등 여러 개발자가 개발한 S 프로그래밍 언어의 오픈소스 대안으로 구상되었습니다. R의 설계 철학은 데이터 분석을 위한 사용자 친화적인 환경을 제공하는 데 중점을 두었으며, 확장성과 사용 용이성에 중점을 두었습니다(Ihaka & Gentleman, 1996).

수년 동안 R은 전 세계 개발자와 연구 커뮤니티의 기여로 인해 상당한 개선을 거쳤습니다. 커뮤니티에 의해 개발된 함수와 데이터 세트를 모은 R 패키지를 호스팅하기 위해 종합 R 아카이브 네트워크(CRAN)가 설립되었습니다. 2024년 기준으로, CRAN에는 생물통계학 및 역학을 포함한 다양한 학문 분야를 위한 통계 방법, 기계 학습 알고리즘 및 특수 도구를 다루는 18,000개 이상의 패키지가 있습니다(CRAN, 2024).

### R과 의학연구

R이 의학연구에서 중요한 도구로 자리잡게 된 이유는 그 유연성, 강력한 통계 기능, 그리고 특화된 패키지의 사용 가능성 때문입니다. 예를 들어, Terry Therneau가 개발한 survival 패키지는 임상 시험 및 역학 연구에서 중요한 방법인 생존 분석을 위한 종합적인 도구 모음을 제공합니다(Therneau, 2000). 또한, caret 패키지는 예측 모델을 구축하고 평가하는 과정을 간소화하여, 정밀 의학에서 개별 환자에게 맞춘 치료를 제공하는 데 점점 더 많이 사용되고 있습니다(Kuhn, 2008).

R이 의학연구에서 중요한 이유 중 하나는 방대하고 복잡한 데이터 세트를 처리할 수 있는 능력입니다. 의료데이터가 점점 더 디지털화됨에 따라 연구자들은 방대한 이질적인 데이터를 분석하는 도전에 직면하게 됩니다. R의 데이터 조작 및 시각화 기능, 특히 dplyr 및 ggplot2 와 같은 패키지를 통해 연구자들은 데이터를 효과적으로 탐색하고 해석할 수 있으며, 전통적인 방법으로는 놓칠 수 있는 인사이트를 발견할 수 있습니다(Wickham, 2016).

의학연구의 복잡성이 증가하고 빅데이터의 부상이 가속화됨에 따라, R은 의료 연구자들에게 중요한 도구로 자리잡았습니다. 다양한 소스의 데이터를 통합하고, 복잡한 통계 분석을 수행하며, 재현 가능한 연구를 생성할 수 있는 능력은 현대 의학연구에서 R을 필수적인 도구로 만들고 있습니다. 또한, R의 오픈소스 특성은 연구자들이 협력하고 그들의 방법을 공유할 수 있도록 하여, 더 강력하고 투명한 과학적 실천을 가능하게 합니다.

의학연구 분야가 계속 진화함에 따라 R의 중요성은 더욱 커질 것입니다. 환자의 유전자 프로필에 기반한 개별 맞춤 치료가 이루어지는 정밀 의학과 같은 새로운 분야는 R이 제공하는 고급 분석 기능에 크게 의존하고 있습니다. 또한, 임상 연구에 기계 학습 방법을 통합하는 작업은 R을 통해 환자 치료에서 새로운 인사이트와 혁신을 가져올 것으로 기대됩니다.


### References

-   Ihaka, R., & Gentleman, R. (1996). R: A language for data analysis and graphics. *Journal of Computational and Graphical Statistics*, 5(3), 299-314.
-   Therneau, T. (2000). A package for survival analysis in S. *Mayo Clinic*.
-   Kuhn, M. (2008). Building predictive models in R using the caret package. *Journal of Statistical Software*, 28(5), 1-26.
-   Wickham, H. (2016). ggplot2: Elegant graphics for data analysis. *Springer-Verlag*.
-   Huber, W., Carey, V. J., Gentleman, R., et al. (2015). Orchestrating high-throughput genomic analysis with Bioconductor. *Nature Methods*, 12(2), 115-121.
-   Harrell, F. E. (2015). Regression modeling strategies: With applications to linear models, logistic and ordinal regression, and survival analysis. *Springer*.
